# Github Actions configuration file
name: Build binaries

on:
  push:
    tags:
      - "*.*.0"

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-18.04
            package: makeself
          
          - os: windows-latest
            package: NSIS
          
          - os: macos-latest
            package: makeself
          
    steps:
    - name: Setup MSVC
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86
        
    - name: Install OpenSSL on Windows
      if: runner.os == 'Windows'    
      uses: crazy-max/ghaction-chocolatey@v1.6.0
      with:
        args: install openssl --no-progress
        
    - name: Setup Linux/gcc-8
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install g++-8
        echo 'CC=gcc-8' >> $GITHUB_ENV
        echo 'CXX=g++-8' >> $GITHUB_ENV      
        sudo apt-get install libasio-dev libgtk-3-dev
        
    - name: Setup MacOS
      if: runner.os == 'macOS'
      run: |
        brew install openssl
        echo 'OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl@3/include' >> $GITHUB_ENV
        echo 'OPENSSL_ROOT_DIR=/usr/local/opt/openssl@3' >> $GITHUB_ENV
        
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
        
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DBUILD_WEBRECORDER=true -DCMAKE_INSTALL_PREFIX=dist
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
      
    - name: Install
      run: cmake --install ${{github.workspace}}/build --config Release
      
    - name: Package
      if: matrix.config.package != 'makeself'
      run: cpack -G ${{ matrix.config.package }} --config ${{github.workspace}}/build/CPackConfig.cmake
      
    - name: Create makeself Installer
      if: matrix.config.package == 'makeself'
      run: |
        cd "${{github.workspace}}"
        cp "deploy/makeself-setup.sh" "dist/setup.sh"
        cp "deploy/hamster-mozilla.json" "dist/"
        wget "https://github.com/megastep/makeself/releases/download/release-2.4.5/makeself-2.4.5.run"
        chmod +x makeself-*.run && ./makeself-*.run --target .
        ./makeself.sh "dist" "BookmarkHamster-${{ github.ref_name }}-${{ runner.os }}-${{ runner.arch }}.run" "Bookmark Hamster" "./setup.sh"      

    - name: Upload to Github release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "BookmarkHamster-*"
        tags: true
        draft: false

